name: Terraform Run

on:
  workflow_call:
    inputs:
      AWS_REGION:
        type: string
        required: true
      spec:
        description: "Path to the Digger config file."
        required: true
        type: string
      run_name:
        description: "Optional name for the run."
        required: false
        type: string
    secrets:
      AWS_IAM_ROLE:
        required: true

jobs:
  digger-job:
    name: Digger Job
    runs-on: ubuntu-latest
    # This is ignored when called, but good for clarity
    # add these permissions to your workflow
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Job id
      run: echo "Job id ${{ fromJSON(github.event.inputs.spec).job_id }}"

    - name: Debug Digger Spec
      run: echo '${{ inputs.spec }}'
    
    - uses: diggerhq/digger@v0.6.97
      name: ${{ inputs.run_name || 'Digger Run' }}
      with:
        setup-aws: true
        setup-terraform: true
        digger-spec: ${{ inputs.spec }}
        aws-role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
        aws-region: ${{ inputs.AWS_REGION }}
        upload-plan-destination: github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}